
CREATE OR REPLACE TRIGGER trg_pagado_s
BEFORE INSERT OR UPDATE ON pedido_cliente
FOR EACH ROW
BEGIN
    IF :NEW.PAGADO = 'S' THEN
        -- Insertar en la tabla VENTA
        INSERT INTO VENTA (id_pedido_cliente, fecha)
        VALUES (:NEW.ID_PEDIDO_CLIENTE, CURRENT_DATE);
    END IF;
END;
/

SELECT * FROM VENTA;
SELECT * FROM PRODUCTO;
SELECT * FROM PEDIDO_CLIENTE;

INSERT INTO PEDIDO_CLIENTE (DNI, N_SERIE_PEDIDO, PAGADO)
VALUES ('123123', 'TEST0002', 'N');
UPDATE PEDIDO_CLIENTE SET pagado='S';